### ISSUE TITLE
Infrastructural improvements related to `pacman`

### ISSUE THREAD

**Issue by chainsawriot** [paulcbauer/apis_for_social_scientists_a_review#29]
As the book is relying on `pacman`, there are a few improvements that we can make

- [x] Use `p_load_gh`

https://github.com/paulcbauer/apis_for_social_scientists_a_review/blob/71c80c57b52ec57b5d53a752079130d329528849/01-introduction.Rmd#L44-L47

- [x] Make this "single source of truth" as this bunch of code has been repeated many times throughout the book

https://github.com/paulcbauer/apis_for_social_scientists_a_review/blob/71c80c57b52ec57b5d53a752079130d329528849/01-introduction.Rmd#L28-L39

**Comment by paulcbauer** [comment]
Not sure this is possible. knitr::current_input() returns the filename of the full rmd "2021_apis_for_social_scientists_a_collaborative_review.Rmd" which includes all the chapters and allows for extracting the packages used across all chapters.

I couldn't find a corresponding knitr function to return the names of the .rmds of the single chapters, e.g., "04-Crowdtangle_api.Rmd". 

But we could certainly replace the code that is repeated across the chapters with a function that is defined in index.Rmd and subsequently used in the single chapters only taking the chapter name, e.g., "Crowdtangle_api" as an argument.

**Comment by chainsawriot** [comment]
@paulcbauer Something like this suffices.
``` r
setwd("~/dev/apis_for_social_scientists_a_review")
.gen_pacman_chunk <- function(x = NULL) {
  if (is.null(x)) {
    file_name <- knitr::current_input()
  } else {
    file_name <- stringr::str_subset(dir(), x)[1]
  }
  lines_text <- readLines(file_name) 
  packages <- gsub("library\\(|\\)", "",  
                  unlist(stringr::str_extract_all(lines_text,  
                                         "library\\([a-zA-z0-9]*\\)|p_load\\([a-zA-z0-9]*\\)"))) 
  packages <- packages[packages!="pacman"] 
  packages <- packages[packages!="p_load("] 
  packages <- paste("# install.packages('pacman')", "library(pacman)", "p_load('", paste(packages, collapse="', '"), "')",sep="") 
  packages <- stringr::str_wrap(packages, width = 80) 
  packages <- gsub("install.packages\\('pacman'\\)", "install.packages\\('pacman'\\)\n", packages) 
  packages <- gsub("library\\(pacman\\)", "library\\(pacman\\)\n", packages)
  cat(packages)
  invisible(x)
}

.gen_pacman_chunk("Crowdtangle")
#> # install.packages('pacman')
#> library(pacman)
#> p_load('httr', 'devtools',
#> 'RCrowdTangle', 'dplyr', 'jsonlite')
.gen_pacman_chunk("Facebook_ads")
#> # install.packages('pacman')
#> library(pacman)
#> p_load('httr', 'remotes', 'dplyr',
#> 'ggplot2', 'tidyr', 'Radlibrary', 'dplyr', 'tidyr', 'DT')
```

<sup>Created on 2022-02-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
