### ISSUE TITLE
unnecessary files

### ISSUE THREAD

**Issue by chainsawriot** [paulcbauer/apis_for_social_scientists_a_review#3]
I think the following files/directories are not needed.

* `rsconnect` (I don't think it should be committed)
* `2021_apis_for_social_scientists_a_collaborative_review.log` (not useful to commit the every changing log)
* `.Rproj.user/shared/notebooks` (it is empty anyway)
* `_bookdown_files` (unless you use travis; if not it creates reproducibility issues and it is big! 10MB and counting)

This one is optional; you can keep this if you want to have the local HTML preview

* `_book` (unless you use Github Page and it points to this directory)

BTW, do you really use Docker to build the book? I think most of the shell scripts are not very useful too.

**Comment by paulcbauer** [comment]
Sorry compiling can't work.. you would need various keys for that. But if you want to compile at some point let us know.

**Comment by chainsawriot** [comment]
I don't have the Google json file. But it also raises a question: do you really need to make the Google API requests every time you render the book?

Take the Google NLP chapter as an example

https://github.com/paulcbauer/apis_for_social_scientists_a_review/blob/807f7f5968ce57f16e14bce74bc9791b796daf3d/05-Google_NLP_API.Rmd#L98-L139

I would have another R file (let's name this: `gen_nlp_results.R`) which has this content:

```r
ibrary(googleLanguageR)
library(tidyverse)
library(tm)
gl_auth("./keys/trustme-312210-b9734c074f6f.json")
guardian_corpus <- quanteda.corpora::download("data_corpus_guardian") 
 text <- guardian_corpus[["documents"]][["texts"]] 
 text <- text[1:20] 
 df <- as.data.frame(text) 
 df <- tibble::rowid_to_column(df, "ID") 
 syntax_analysis <- gl_nlp(df$text, nlp_type = "analyzeSyntax") 
saveRDS(df, "figures/nlp_df.RDS")
saveRDS(syntax_analysis, "figures/nlp_syntax_analysis.RDS")
```

In the Rmarkdown file, you can then turn the chunk option `eval` to `FALSE`

And add this chunk to "fake" the request.

```{r, eval = TRUE, echo = FALSE}
df <- readRDS("figures/nlp_df.RDS")
syntax_analysis <- readRDS("figures/nlp_syntax_analysis.RDS")
```

The rest of the chunks would run. So the API requests and rendering are decoupled. Those who have the keys can run `gen_nlp_results.R` to refresh the results. Those who don't have the keys can still render the book.
