### ISSUE TITLE
Decouple chapter order from file naming

### ISSUE THREAD

**Issue by MKyhos** [paulcbauer/apis_for_social_scientists_a_review#31]
I mentioned that currently, the chapter order is ultimately defined by the file naming, which comes with the benefit that the chapters order naturally also in the local directory, etc.

However, this comes at the cost that any newly added chapter inserted between existing chapters makes it necessary to rename a bunch of files. This clutters the git history and also might be a bit tedious work, as sometimes (most of the time), the file name is also referenced within the file.

**Proposal**

- Rename chapter files coherently, eg. to `chapter_{name of the API}.Rmd`
- Take care of the ordering in `_bookdown.yml` via `rmd_files` field, see https://bookdown.org/yihui/bookdown/usage.html#usage

**Comment by chainsawriot** [comment]
@MKyhos This is a nice solution! The operation in #14 can still take place by reading `_bookdown.yml`, modifying it in-place (it is machine-readable with packages such as [yaml](https://cran.r-project.org/web/packages/yaml/index.html) and [ymlthis](https://ymlthis.r-lib.org/)), and overwriting the yaml (and compiling the book).

**Comment by paulcbauer** [comment]
Sounds great. Would you like to implement it (test it in your fork) and create a pull request? Otherwise, I should also have time to implement it in the next few days.

**Comment by chainsawriot** [comment]
@paulcbauer I don't know if the "you" mentioned is plural or not. But I can do that.
